version: '3.9'
services:
  api:
    build: .
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - 3000:3000
    tty: true
    command: sh
  db:
    image: mysql:8.0.28
    platform: linux/amd64
    container_name: mysql-container
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sample
      TZ: 'Asia/Tokyo'
    volumes:
      - ./mysql/data-volume:/var/lib/mysql
